### ISSUE TITLE
Add statement tagging

### ISSUE THREAD

**Issue by furf** [Lessig2016/fixdemocracyfirst#10]
We would like to implement a tagging feature for statements and admin interface for Fix Democracy First.

A tag is a short categorical description of a statement, i.e. celebrity, issue, global warming.

* An admin can add tags to a statement.
* An admin can remove tags from a statement.
* An admin can view a list of tags.
* An admin can delete a tag and remove it from all statements at once.
* A user can see all statements of a certain tag on a separate page.
* A user can jump to a tag page via a dropdown on the home page.

Sample tasks:

* Create tags model: id, name (normalized)
* Create join model (statements_tags)
* Add easy-to-use interface for adding/removing tags to/from video via admin interface
* Add list view for tags with edit/delete functionality
* Add tag page
* Add tag dropdown to homepage

**Comment by furf** [comment]
:+1:

**Comment by ricardojr** [comment]
How can I get access to the slack channel? @furf

**Comment by furf** [comment]
Take a look at our [Team Lessig Tech repo](https://github.com/Lessig2016/Lessig2016.github.io) for information. Basically, fill out the brief [tech volunteer registration](http://goo.gl/forms/1rwP1lOjbU) and I'll email you an invite shortly after.

**Comment by bev-a-tron** [comment]
Ok, I'm going to try to do this!  Having some problems getting admin working on my local...
